@Resturants.API_HostAddress = https://localhost:7231



GET {{Resturants.API_HostAddress}}/api/restaurants

###

GET {{Resturants.API_HostAddress}}/api/restaurants

###

GET {{Resturants.API_HostAddress}}/api/restaurants/2

###

GET {{Resturants.API_HostAddress}}/api/restaurants

###

POST {{Resturants.API_HostAddress}}/api/restaurants
Content-Type: application/json
{
  "name": "Spicy Delights3",
  "description": "A culinary experience like no other",
  "category": "Egypt",
  "hasDelivery": true,
  "contactEmail": "info@gourmetdelights.com",
  "contactNumber": "555-123-4567",
  "city": "Metropolis",
  "street": "456 Gourmet Avenue",
  "postalCode": "54-321"
}
###

POST {{Resturants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  //CreateResturantDto
}

###

POST {{Resturants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  //CreateResturantDto
}

###

GET {{Resturants.API_HostAddress}}/api/restaurants

###

@id=5
GET {{Resturants.API_HostAddress}}/api/restaurants/{{id}}

###

POST {{Resturants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  //CreateResturantDto
}

###

GET {{Resturants.API_HostAddress}}/api/restaurants/{{id}}

###

GET {{Resturants.API_HostAddress}}/api/restaurants/{{id}}

###
